runtime: python
api_version: 1
threadsafe: yes
env: flex
service: emulator
entrypoint: python manage.py runserver 0.0.0.0:$PORT

runtime_config:
  python_version: 2

handlers:
- url: /static
  static_dir: static/

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^env/.*$

health_check:
  enable_health_check: False
