# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_url', models.CharField(default='/done/', help_text='Redirect to url, if iframe processing is success', max_length=255)),
                ('failure_url', models.CharField(default='/done/', help_text='Redirect to url, if iframe processing is faild', max_length=255)),
                ('transaction_password', models.CharField(blank=True, help_text='Can be received as TranzilaPW-field in request. Checking if present', max_length=255, null=True)),
                ('include_cc', models.BooleanField(default=False, help_text='Return full Card number in iframe response if enabled, or last 4 digits else')),
                ('generate_errors', models.BooleanField(default=True, help_text='If enabled - system return random errors during processing')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tokenization',
            fields=[
                ('token', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('ccno', models.CharField(db_index=True, max_length=20)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ccno', models.CharField(max_length=20)),
                ('Response', models.CharField(max_length=5)),
                ('TranzilaTK', models.CharField(max_length=20)),
                ('Tempref', models.CharField(max_length=10)),
                ('ConfirmationCode', models.CharField(max_length=10)),
                ('benid', models.CharField(max_length=40)),
                ('sum', models.FloatField()),
                ('csum', models.FloatField(default=0.0)),
                ('dsum', models.FloatField(default=0.0)),
                ('expmonth', models.CharField(max_length=4)),
                ('expyear', models.CharField(max_length=4)),
                ('expdate', models.CharField(max_length=6)),
                ('cred_type', models.CharField(max_length=5)),
                ('currency', models.IntegerField()),
                ('cardtype', models.IntegerField()),
                ('cardissuer', models.IntegerField()),
                ('cardaquirer', models.IntegerField()),
                ('lang', models.CharField(max_length=5)),
                ('myid', models.CharField(max_length=5)),
                ('Responsesource', models.IntegerField(default=0)),
                ('Responsecvv', models.IntegerField(default=0)),
                ('Responseid', models.IntegerField(default=0)),
                ('params', models.TextField(default='{}')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
