# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tr_emulator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Responsecvv',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Responseid',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Responsesource',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='TranzilaTK',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='benid',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cardaquirer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cardissuer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cardtype',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ccno',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cred_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='expdate',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='expmonth',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='expyear',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='myid',
        ),
        migrations.AddField(
            model_name='transaction',
            name='tranmode',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
